import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import './globals.css'


const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Vidya-ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
        >
          <Toaster/>
            {children}
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
